name: carrot-detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.0
  - ipykernel=6.29.5
  - jupyterlab
  - numpy=2.2.1
  - pandas=2.2.3
  - matplotlib=3.9.2
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pip
  - pip:
      - scikit-learn==1.5.2
      - torchsummary
